export const programmingSkills = [
  { name: "Typescript", percentage: 100 },
  { name: "React", percentage: 100 },
  { name: "NodeJS", percentage: 95 },
  { name: "Python", percentage: 95 },
  { name: "PostgreSQL", percentage: 95 },
  { name: "NoSQL", percentage: 90 },
  { name: "Docker", percentage: 95 },
  { name: "Terraform", percentage: 100 },
  { name: "NextJS", percentage: 90 },
  { name: "AWS", percentage: 95 },
  { name: "GCP", percentage: 90 },
  { name: ".NET / C#", percentage: 80 },
  { name: "Go", percentage: 85 },
];
